
service: poliza

provider:
  name: aws
  runtime: nodejs12.x

functions:
  poliza:
    handler: handler.calculate
    events:
      - http:
          path: poliza
          method: get
    

plugins:
  - serverless-offline
